### ISSUE TITLE
Enable automatic PyPI deployment on tag cut

### ISSUE THREAD

**Issue by webknjaz** [atlassian/asap-authentication-python#40]
Hi,

I just wanted to point you out that there's an option of having new package version automatically deployed to [PyPI deployment](https://docs.travis-ci.com/user/deployment/pypi/) once you release a new tag.

Corresponding section in `.travis.yml` would look as follows:
```yaml
deploy:
  on:
    tags: true
  provider: pypi
  distributions: sdist bdist_wheel
  user: dblack
  password:
    secure: [Your encrypted password](https://docs.travis-ci.com/user/encryption-keys/)
```

*Don't forget to [encrypt the password](https://docs.travis-ci.com/user/encryption-keys/).
